#!/bin/bash -x
export VERSION="$1"
export BUILDTYPE="${2:-tagged}"


die () {
case $1 in 
 1) echo "Build Error:" 
   echo "Build Version: ${VERSION} and git Version: ${gitver} don't match"
   echo "Bump version or build from master with  ./build ${VERSION} master"
   exit 1
   ;;
 2) echo "git checkout failed" 
    echo "Didnt find TAG for ${VERSION}"
    exit 2
    ;;
 *) echo "ERROR: die called exit $1"
    exit $1
    ;;
esac
}
echo "Making packages"

mkdir -pv /root/repo

git clone https://github.com/mazaclub/electrum-frc /root/repo

cd /root/repo
if [ "${BUILDTYPE}" = "master" ] 
then 
 echo "building from MASTER" 
 export gitver=$(grep "ELECTRUM_VERSION" lib/version.py |awk '{print $3}' |cut  -d"\"" -f2)
 if [ "${VERSION}" != "${gitver}" ]
 then 
   sed -i 's/ELECTRUM_VERSION\ \=\ \"'${gitver}'\"/ELECTRUM_VERSION\ \=\ \"'${VERSION}'\"/g' lib/version.py
 fi
else "Building from Tagged Version: ${VERSION}" 
   git checkout v${VERSION} || die 2
fi
cp -v  /root/make_packages /root/repo/make_packages
cp -v  /root/make_android /root/repo/make_android
cp -v  /root/make_windows /root/repo/make_windows
cd /root/repo
mkdir ./packages
./make_packages
mv dist /releases/source
pip install --no-compile -t packages -r /root/requirements.txt
cp -av /root/packages ./
mkdir dist
./make_android
mv dist /releases/android
mkdir dist
./make_windows
cp -av dist /releases/windows
## rm just isn't that expensive to run without fancy bash expansions

rm -rf /opt/wine-electrum/drive_c/electrum-frc/Electrum-frc-$VERSION.*
rm -rf /opt/wine-electrum/drive_c/electrum-frc/Electrum-frc-$VERSION/
rm -rf /opt/wine-electrum/drive_c/electrum-frc/Electrum-frc-$VERSION*

cp -v /root/repo/dist/Electrum-frc-$VERSION.zip /opt/wine-electrum/drive_c/electrum-frc/Electrum-frc-$VERSION.zip
cd /opt/wine-electrum/drive_c/electrum-frc
unzip Electrum-frc-$VERSION.zip
#mv Electrum-frc-$VERSION/packages/google/protobuf Electrum-frc-$VERSION/packages/google.protobuf
#mv Electrum-frc-$VERSION/packages/protobuf* Electrum-frc-$VERSION/packages/google.protobuf/
